---
- name: Validate variable database_role
  fail:
    msg: "database role is not set or incorrect"
  when: database_role is not defined or database_role not in ['main', 'replicant']
  tags: all

- import_tasks: install.yml
  become: true
  tags: mysql-install

- import_tasks: databases_and_users.yml
  become: true
  become_user: mysql
  vars:
    ansible_ssh_pipelining: true
  tags: mysql-setup
  when: database_role == 'main'

- import_tasks: backup_script.yml
  become: true
  tags:
    - mysql-setup
    - backup-script
  when: database_role == 'replicant'
