# These tasks should only be run on the replicant database server

- name: Create /srv/backup
  become: true
  file:
    path: /srv/backup
    state: directory
    owner: root
    group: root
    mode: 0700
  tags: backup

- name: Copy backup script
  become: true
  template:
    src: backup.j2
    dest: /usr/local/bin/backup
    owner: root
    group: root
    mode: 0755
  tags: backup
