# These tasks should only be run on the replicant database server

- name: Create /srv/backup
  become: true
  file:
    path: /srv/backup
    state: directory
    owner: root
    group: root
    mode: 0700
  tags: backup

- name: Copy backup script
  become: true
  template:
    src: backup.j2
    dest: /usr/local/bin/backup
    owner: root
    group: root
    mode: 0755
  tags: backup

# note: our server is set to UTC, which is 5 hours
# ahead of East coast time.

- name: LittleSis database backup job
  become: true
  cron:
    name: "Backup littlesis database"
    minute: "0"
    hour: "7"
    job: "/usr/local/bin/backup littlesis"
  tags: cron
    
- name: Wordpress database backup job
  become: true
  cron:
    name: "Backup wordpress database"
    minute: "0"
    hour: "6"
    job: "/usr/local/bin/backup wordpress"
  tags: cron
