---
- name: Remove all anonymous mysql user accounts
  mysql_user:
    name: ''
    host_all: yes
    login_unix_socket: "{{ database_unix_socket }}"
    state: absent
  tags: mysql-config

- name: Create littlesis database
  mysql_db:
    name: "{{ database_littlesis_name }}"
    state: present
    login_unix_socket: "{{ database_unix_socket }}"
  when: database_role == 'main'
  tags: mysql-config

- name: Create wordpress database
  mysql_db:
    name: "{{ database_wordpress_name }}"
    state: present
    login_unix_socket: "{{ database_unix_socket }}"
  when: database_role == 'main'
  tags: mysql-config

- name: Create littlesis database user
  mysql_user:
    host: "{{ internal_ip_app }}"
    name: "{{ database_littlesis_name }}"
    password: "{{ database_littlesis_password }}"
    login_unix_socket: "{{ database_unix_socket }}"
    priv: "{{ database_littlesis_name }}.*:ALL"
    state: present
  when: database_role == 'main'

# - name: Create wordpress database user
#   mysql_user:
#     host: "{{ internal_ip_wordpress }}"
#     name: "{{ database_wordpress_name }}"
#     password: "{{ database_wordpress_password }}"
#     login_unix_socket: "{{ database_unix_socket }}"
#     priv: "{{ database_wordpress_name }}.*:ALL"
#     state: present
#   when: database_role == 'main'

- name: Create replicant database user
  mysql_user:
    host: "{{ internal_ip_replicant }}"
    name: "{{ database_replicant_name }}"
    password: "{{ database_replicant_password }}"
    login_unix_socket: "{{ database_unix_socket }}"
    priv: "*.*:REPLICATION SLAVE"
    state: present
  when: database_role == 'main'
