version: '3'

volumes:
  postgres-data:

services:
  app:
    image: littlesis/rails:latest
    stdin_open: true
    tty: true
    shm_size: '2gb'
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./rails:/littlesis
      - ./docker/config/lilsis.yml:/littlesis/config/lilsis.yml
      - ./docker/config/database.yml:/littlesis/config/database.yml
      - ./docker/tmp:/littlesis/tmp
    depends_on:
      - redis
      - postgres
    environment:
      - RAILS_ENV=development
      - LITTLESIS_BIND=tcp://0.0.0.0:8080
      - RAILS_SERVE_STATIC_FILES=true
      - WEB_CONCURRENCY=1
    extra_hosts:
      - "test.host:127.0.0.1"

  redis:
    image: redis:6

  mysql:
    image: mariadb:10.5
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/config/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root

  postgres:
    image: postgres:13
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    shm_size: '2gb'
    volumes:
      - ./docker/config/postgresql.conf:/etc/postgresql.conf
      - postgres-data:/var/lib/postgresql/data

    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_PASSWORD: themanbehindthemanbehindthethrone
      POSTGRES_USER: littlesis


  nginx:
    image: nginx:latest
    ports:
       - "127.0.0.1:8081:80"
    volumes:
      - ./rails:/littlesis
      - ./static:/var/www/static
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/log:/var/log/nginx
    depends_on:
      - app
