development:
  adapter: postgresql
  database: littlesis
  username: littlesis
  password: themanbehindthemanbehindthethrone
  host: postgres

test:
  adapter: postgresql
  database: littlesis_test
  username: littlesis
  password: themanbehindthemanbehindthethrone
  host: postgres
