---
- import_tasks: security.yml
  tags: security

- import_tasks: swap.yml
  tags: swap

- name: update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: upgrade apt packages
  apt: upgrade=yes

- name: Install Common Packages
  apt:
    pkg: "{{ littlesis_common_packages }}"
