---
- name: update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: packages

- name: upgrade apt packages
  apt: upgrade=yes
  tags: packages

- name: Install common Packages
  apt:
    pkg: "{{ littlesis_common_packages }}"
  tags: packages

- import_tasks: swap.yml
  tags: swap

- import_tasks: user.yml
  tags: user

- import_tasks: security.yml
  tags: security


