---
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: packages

- name: Upgrade apt packages
  become: yes
  apt: upgrade=yes
  tags: packages

- name: Add buster-backports
  become: yes
  apt_repository:
    repo: 'deb http://deb.debian.org/debian buster-backports main'
    state: present
    update_cache: yes


- name: Install common Packages
  become: yes
  apt:
    pkg: "{{ littlesis_common_packages }}"
  tags: packages

- import_tasks: mariadb.yml
  become: yes
  tags: mariadb-client

- import_tasks: swap.yml
  become: yes
  tags: swap

- import_tasks: user.yml
  become: yes
  tags: user

- import_tasks: security.yml
  become: yes
  tags: security

- import_tasks: rclone.yml
  become: yes
  tags: rclone
