---
- name: Add MariaDB apt key (F1656F24C74CD1D8)
  become: yes
  apt_key:
    data: "{{ lookup('file', 'F1656F24C74CD1D8.asc') }}"
    state: present

- name: Add Mariadb repo
  become: yes
  apt_repository:
    repo: 'deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.5/debian buster main'
    state: present
    update_cache: yes

- name: Install Mariadb client
  become: yes
  apt:
    update_cache: yes
    name: mariadb-client
