---
- name: Install rclone
  apt:
    name: rclone
    state: present

- name: Create rclone directory
  file:
    path: /root/.config/rclone
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Create rclone configuration
  template:
    src: rclone.conf.j2
    dest: /root/.config/rclone/rclone.conf
    owner: root
    group: root
    mode: 0600
