---
- name: Write swapfile
  command: fallocate -l {{ swapfile_size }} {{ swapfile_location }} creates={{ swapfile_location }}
  register: write_swapfile
  when: swapfile_size != false

- name: Set swapfile permissions
  file: path={{ swapfile_location }} mode=600
  when: swapfile_size != false

- name: Create swapfile
  command: mkswap {{ swapfile_location }}
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed

- name: Enable swapfile
  command: swapon {{ swapfile_location }}
  when: swapfile_size != false and create_swapfile.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swapfile_location }}   none    swap    sw    0   0" state=present
  when: swapfile_size != false


# Adapted from: https://github.com/kamaln7/ansible-swapfile/blob/master/tasks/main.yml
