# This loads a copy of our wordpress production database
- hosts: database
  vars_files: ["../vars.yml"]
  tasks:
    - name: Copy database dump file
      become: yes
      copy:
        src: "{{ wordpress_sql_dump_file }}"
        owner: mysql
        dest: /tmp

    - name: Restore database
      become: yes
      become_user: mysql
      mysql_db:
        login_user: "{{ database_wordpress_name }}"
        login_password: "{{ database_wordpress_password }}"
        name: "{{ database_wordpress_name }}"
        state: import
        target: "/tmp/{{ wordpress_sql_dump_file | basename }}"
