---
- name: Create wordpress group
  become: yes
  group:
    name: wordpress
    state: present

- name: Create wordpress user
  become: yes
  user:
    name: wordpress
    group: wordpress
    shell: /bin/bash

- name: Install php packages
  become: yes
  apt:
    update_cache: yes
    name: "{{ littlesis_php_packages }}"

- name: Remove stock www php pool configuration
  become: yes
  file:
    state: absent
    path: /etc/php/7.3/fpm/pool.d/www.conf
  notify: restart php-fpm
  tags: fpm

- name: Update weird path thingy in php.ini
  become: yes
  lineinfile:
    regexp: 'cgi.fix_pathinfo='
    line: 'cgi.fix_pathinfo=0'
    path: /etc/php/7.3/fpm/php.ini
  notify: restart php-fpm
  tags: fpm

- name: Copy wordpress fpm pool configuration
  become: yes
  template:
    src: pool.conf.j2
    dest: /etc/php/7.3/fpm/pool.d/wordpress.conf
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  tags: fpm

- name: Download WP-CLI
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    owner: root
    group: root
    mode: 0755

- name: Install Composer
  script: ./scripts/composer_setup.sh
  tags: composer

- name: create /var/www/wordpress
  become: yes
  file:
    path: /var/www/wordpress
    state: directory
    owner: wordpress
    group: www-data
    mode: 0755

- name: Download WordPress
  become: yes
  get_url:
    url: "{{ wordpress_url }}"
    dest: "/tmp/{{ wordpress_url | basename }}"
    checksum: "{{ wordpress_checksum }}"
  tags: install

- name: Extract wordpress
  become: yes
  unarchive:
    src: "/tmp/{{ wordpress_url | basename }}"
    dest: /var/www/wordpress
    owner: wordpress
    group: wordpress
    mode: 0755
    remote_src: yes
    creates: /var/www/wordpress/wordpress

- name: Setup littlesis-packages repo
  become: yes
  become_user: wordpress
  git:
    repo: https://github.com/public-accountability/pai-packages.git
    dest: /var/www/wordpress/pai-packages
    force: yes
    version: master

- name: Install PHP Packages with Composer
  become: yes
  become_user: wordpress
  composer:
    command: install
    no_dev: true
    working_dir: /var/www/wordpress/pai-packages

- name: Change ownership of WordPress installation
  become: yes
  file:
    path: /var/www/wordpress
    owner: wordpress
    group: wordpress
    mode: 0755
    state: directory
    recurse: yes
  tags: wordpress-permissions

- name: create /var/www/wordpress/wordpress/wp-content/uploads
  become: yes
  become_user: wordpress
  file:
    path: /var/www/wordpress/wordpress/wp-content/uploads
    state: directory
    owner: wordpress
    group: wordpress
    mode: 0755


- name: Copy wp-config.php
  become: yes
  become_user: wordpress
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wordpress/wp-config.php
    mode: 0644
    owner: wordpress
    group: wordpress
  notify: restart php-fpm
  tags: config

- name: set wordpress directory permissions
  become: yes
  become_user: wordpress
  command: find /var/www/wordpress -type d -exec chmod 755 {} +
  tags: wordpress-permissions

- name: Install nginx
  become: yes
  apt:
    update_cache: yes
    name: nginx
  tags: nginx

- name: Create /etc/nginx/certs folder
  become: yes
  file:
    path: /etc/nginx/certs
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: nginx

- name: Copy news TLS Cert
  become: yes
  copy:
    content: "{{ news_tls_certificate }}"
    dest: /etc/nginx/certs/news_certificate.pem
    owner: root
    group: root
    mode: 0640
  no_log: true

- name: Copy new TLS Key
  become: yes
  copy:
    content: "{{ news_tls_key }}"
    dest: /etc/nginx/certs/news_key.pem
    owner: root
    group: root
    mode: 0640
  no_log: true

- name: Copy pai TLS Cert
  become: yes
  copy:
    content: "{{ pai_tls_certificate }}"
    dest: /etc/nginx/certs/pai_certificate.pem
    owner: root
    group: root
    mode: 0640
  no_log: true
  
- name: Copy pai TLS Key
  become: yes
  copy:
    content: "{{ pai_tls_key }}"
    dest: /etc/nginx/certs/pai_key.pem
    owner: root
    group: root
    mode: 0640
  no_log: true

- name: Copy wordress server shared configuration
  become: yes
  template:
    src: wordpress_server.conf.j2
    dest: /etc/nginx/wordpress_server.conf
    owner: root
    group: root
    mode: 0640
  notify: restart nginx
  tags: nginx

- name: Copy nginx site configurations
  become: yes
  template:
    src: wordpress-nginx.conf.j2
    dest: /etc/nginx/sites-enabled/wordpress.conf
    owner: root
    group: root
    mode: 0640
  notify: restart nginx
  tags: nginx

- name: Copy nginx configuration
  become: yes
  template:
    src: "{{ nginx_conf_template | default('nginx.conf.j2') }}"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0640
  notify: restart nginx
  tags: nginx

- name: Install wp-content/uploads backup script
  become: true
  copy:
    src: backup-uploads
    dest: /usr/local/bin/backup-uploads
    owner: root
    group: root
    mode: 0755
  tags: backup

- name: Setup wordpress-backup cron
  become: true
  cron:
    name: "backup wp-content/uploads"
    minute: "0"
    hour: "6"
    weekday: "0"
    job: "/usr/local/bin/backup-uploads"
  tags: backup
