---
- name: Add php ppa:odrej/php
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes
  tags: php

- name: Install required packages
  apt:
    update_cache: yes
    name: "{{ littlesis_php_packages }}"
  tags: php

- name: Install python3-pymysql (required for ansible's mysql tasks)
  apt:
    name: python3-pymysql
    state: present

- name: Create wordpress group
  group:
    name: wordpress
    state: present

- name: Create wordpress user
  user:
    name: wordpress
    group: wordpress
    shell: /bin/bash

- name: Create wordpress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: "{{ database_username }}"
    login_host: "{{ database_host }}"
    login_password: "{{ database_password }}"
  tags: database

- name: Copy database dump file
  copy:
    src: "{{ wordpress_database_dump_file }}"
    dest: /tmp
  when: wordpress_restore_from_dump and wordpress_database_dump_file is defined
  tags: database

- name: Restore database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: import
    login_user: "{{ database_username }}"
    login_host: "{{ database_host }}"
    login_password: "{{ database_password }}"
    target: /tmp/{{ wordpress_database_dump_file | basename }}
  when: wordpress_restore_from_dump and wordpress_database_dump_file is defined
  tags: database

- name: create wordpress database user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    host: '%'
    state: present
    login_user: "{{ database_username }}"
    login_host: "{{ database_host }}"
    login_password: "{{ database_password }}"
  tags: database

- name: Download WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    owner: root
    group: root
    mode: 0755
  tags:
    - wp-cli
    - install

- name: Install Composer
  become: yes
  become_user: root
  script: ./scripts/composer_setup.sh
  tags:
    - composer
    - install

- name: create /var/www/wordpress
  file:
    path: /var/www/wordpress
    state: directory
    owner: wordpress
    group: www-data
    mode: 0755
  tags: install

- name: Setup littlesis-packages repo
  become: yes
  become_user: wordpress
  git:
    repo: https://github.com/public-accountability/pai-packages.git
    dest: /var/www/wordpress/pai-packages
    force: yes
    version: master
  tags: install  

- name: Download WordPress
  get_url:
    url: "{{ wordpress_url }}"
    dest: /tmp/wordpress.tar.gz
    checksum: "{{ wordpress_checksum }}"
  when: install_wordpress
  tags: install

- name: Extract wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/wordpress
    owner: wordpress
    group: wordpress
    mode: 0755
    remote_src: yes
    creates: /var/www/wordpress/wordpress
  when: install_wordpress
  tags: install

- name: Install PHP Packages with Composer
  become: yes
  become_user: wordpress
  composer:
    command: install
    no_dev: true
    working_dir: /var/www/wordpress/pai-packages
  tags:
    - install
    - composer

- name: create /var/www/wordpress/wordpress/wp-content/uploads
  file:
    path: /var/www/wordpress/wordpress/wp-content/uploads
    state: directory
    owner: wordpress
    group: wordpress
    mode: 0755
  tags:
    - install

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wordpress/wp-config.php
    mode: 0644
    owner: wordpress
    group: wordpress
  tags: config

- name: Change ownership of WordPress installation
  file:
    path: /var/www/wordpress
    owner: wordpress
    group: wordpress
    mode: 0755
    state: directory
    recurse: yes
  tags: chmod

- name: Change ownership of WordPress installation
  file:
    path: /var/www/wordpress
    owner: wordpress
    group: wordpress
    mode: 0755
    state: directory
    recurse: yes
  tags: chmod

- name: set wordpress directory permissions
  command: find /var/www/wordpress -type d -exec chmod 755 {} +
  tags: chmod

- name: Remove stock www php pool configuration
  file:
    state: absent
    path: /etc/php/7.2/fpm/pool.d/www.conf
  notify: restart php-fpm
  tags: fpm

- name: update weird path thingy in php.ini
  lineinfile:
    regexp: 'cgi.fix_pathinfo='
    line: 'cgi.fix_pathinfo=0'
    path: /etc/php/7.2/fpm/php.ini
  notify: restart php-fpm
  tags: fpm

- name: Copy wordpress fpm pool configuration
  template:
    src: pool.conf.j2
    dest: /etc/php/7.2/fpm/pool.d/wordpress.conf
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  tags: fpm

- name: Install nginx
  apt:
    update_cache: yes
    name: nginx
  tags: nginx

- name: Create /etc/nginx/certs folder
  file:
    path: /etc/nginx/certs
    state: directory
    owner: root
    group: root
    mode: 0750
  tags: nginx

- name: Copy news TLS Cert
  copy:
    content: "{{ news_tls_certificate }}"
    dest: /etc/nginx/certs/news_certificate.pem
    owner: root
    group: root
    mode: 0600
  no_log: true
  tags: nginx

- name: Copy new TLS Key
  copy:
    content: "{{ news_tls_key }}"
    dest: /etc/nginx/certs/news_key.pem
    owner: root
    group: root
    mode: 0600
  no_log: true
  tags: nginx

- name: Copy pai TLS Cert
  copy:
    content: "{{ pai_tls_certificate }}"
    dest: /etc/nginx/certs/pai_certificate.pem
    owner: root
    group: root
    mode: 0600
  no_log: true
  tags: nginx

- name: Copy pai TLS Key
  copy:
    content: "{{ pai_tls_key }}"
    dest: /etc/nginx/certs/pai_key.pem
    owner: root
    group: root
    mode: 0600
  no_log: true
  tags: nginx

- name: Copy wordress server shared configuration
  template:
    src: wordpress_server.conf.j2
    dest: /etc/nginx/wordpress_server.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: nginx

- name: Configure nginx
  include_role:
    name: littlesis
    tasks_from: nginx_config
    apply:
      tags: ['nginx']
  vars:
    nginx_conf_template: roles/wordpress/templates/nginx.conf.j2
  tags: nginx

- name: Copy nginx site configuration
  template:
    src: wordpress-nginx.conf.j2
    dest: /etc/nginx/sites-enabled/wordpress.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: nginx
