---
- name: Add php ppa:odrej/php
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes
  tags: php

- name: Install required packages
  apt:
    update_cache: yes
    name: "{{ littlesis_php_packages }}"
  tags: php

- name: Install python3-pymysql (required for ansible's mysql tasks)
  apt:
    name: python3-pymysql
    state: present

- name: Create wordpress group
  group:
    name: wordpress
    state: present

- name: Create wordpress user
  user:
    name: wordpress
    group: wordpress
    shell: /bin/bash

- name: Create wordpress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: "{{ database_username }}"
    login_host: "{{ database_host }}"
    login_password: "{{ database_password }}"
  tags: database

- name: Copy database dump file
  copy:
    src: "{{ wordpress_database_dump_file }}"
    dest: /tmp
  when: wordpress_restore_from_dump and wordpress_database_dump_file is defined
  tags: database

- name: Restore database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: import
    login_user: "{{ database_username }}"
    login_host: "{{ database_host }}"
    login_password: "{{ database_password }}"
    target: /tmp/{{ wordpress_database_dump_file | basename }}
  when: wordpress_restore_from_dump and wordpress_database_dump_file is defined
  tags: database


- name: create wordpress database user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    host: '%'
    state: present
    login_user: "{{ database_username }}"
    login_host: "{{ database_host }}"
    login_password: "{{ database_password }}"
  tags: database


- name: Download WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    owner: root
    group: root
    mode: 0755
  tags:
    - wp-cli
    - install

- name: Install Composer
  become: yes
  become_user: root
  script: ./scripts/composer_setup.sh
  tags:
    - composer
    - install

- name: create /var/www/wordpress
  file:
    path: /var/www/wordpress
    state: directory
    owner: wordpress
    group: www-data
    mode: 0755
  tags: install

- name: Setup littlesis-packages repo
  become: yes
  become_user: wordpress
  git:
    repo: https://github.com/public-accountability/pai-packages.git
    dest: /var/www/wordpress/pai-packages
    force: yes
    version: master
  tags: install  

- name: Download WordPress
  get_url:
    url: "{{ wordpress_url }}"
    dest: /tmp/wordpress.tar.gz
    checksum: "{{ wordpress_checksum }}"
  when: install_wordpress
  tags: install

- name: Extract wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/wordpress
    owner: wordpress
    group: wordpress
    mode: 0755
    remote_src: yes
    creates: /var/www/wordpress/wordpress
  when: install_wordpress
  tags: install


- name: Install PHP Packages with Composer
  become: yes
  become_user: wordpress
  composer:
    command: install
    no_dev: true
    working_dir: /var/www/wordpress/pai-packages
  tags:
    - install
    - composer

