---
swapfile_size: 4G
swapfile_location: /swapfile

maintainer_user_name: maintainer

maintainer_authorized_keys: []

littlesis_common_packages:
  - build-essential
  - sudo
  - curl
  - git
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - htop
  - sysstat
  - lsof
  - tmux
  - mosh
  - rsync
  - zip
  - unzip
  - rclone
  - python3
  - python3-pip
