---
- name: Copy nginx configuration
  template:
    src: "{{ nginx_conf_template | default('nginx.conf.j2') }}"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: passenger-configure

- name: Copy realip configuration
  copy:
    src: realip.conf
    dest: /etc/nginx/conf.d/realip.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags:
    - passenger-configure

- name: Copy nginx ssl configuration
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: passenger-configure
