---
- name: update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: upgrade apt packages
  apt: upgrade=yes

- name: Install required packages
  apt:
    name: "{{ littlesis_packages }}"

- name: Add mariadb key
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: F1656F24C74CD1D8

- name: Add Mariadb repo
  apt_repository:
    repo: 'deb [arch=amd64,i386,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.2/ubuntu bionic main'
    state: present
    update_cache: yes

- name: Install Mariadb-client
  apt:
    update_cache: yes
    name: 
      - mariadb-client
      - libmariadb-dev

- name: Install geckodriver
  shell: "curl -sSL {{ geckodriver_url }} | tar -C /usr/local/bin/ -xzf - geckodriver"
  args:
    creates: /usr/local/bin/geckodriver

- name: Install nodejs
  include_role:
    name: geerlingguy.nodejs

- name: Add yarn key
  apt_key:
    id: 1646B01B86E50310
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
  tags: yarn

- name: Add yarn apt repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
  tags: yarn

- name: Install Yarn
  apt:
    update_cache: yes
    name: yarn
  tags: yarn

- name: disable snapd
  service:
    name: snapd
    enabled: no
    state: stopped
