---
# If the step after this fails,regenerate the list of missing packages with
# ` rvm requirements `

- name: Install required packages for RVM
  apt:
    update_cache: yes
    name: 
      - bison
      - libgdbm-dev
      - libncurses5-dev
      - libsqlite3-dev
      - libyaml-dev
      - sqlite3
      - libgmp-dev
      - libreadline-dev
      - libssl-dev
    state: installed

# rvm_io.ruby role can be downloaded like this:
# ansible-galaxy install rvm_io.ruby
- name: Install RVM
  include_role:
    name: rvm.ruby
  vars:
    rvm1_rubies:
      - "{{ ruby_version }}"
    rvm1_user: 'littlesis'
    rvm1_install_path: '/home/littlesis/.rvm'
    rvm1_install_flags: '--auto-dotfiles --user-install --autolibs=0'
    rvm1_autolib_mode: 0
