- name: Install firefox-esr and xvfb
  become: yes
  apt:
    pkg:
      - firefox-esr
      - xvfb

- name: Install geckodriver
  unarchive:
    src: "{{ geckodriver_url }}"
    dest: /usr/local/bin
    remote_src: yes

- name: Get geckodriver sha256sum
  stat:
    path: /usr/local/bin/geckodriver
    checksum_algorithm: sha256
    get_checksum: yes
  register: geckodriver_stat

- name: Verify sha256sum of geckodriver
  fail:
    msg: "geckodriver checksum failed."
  when: geckodriver_stat.stat.checksum != geckodriver_checksum
