---
- name: Create littlesis group
  group:
    name: littlesis
    state: present

- name: Create littlesis user
  user:
    name: littlesis
    group: littlesis
    shell: /bin/bash

- name: Install required packages
  apt:
    cache_valid_time: 3600
    update_cache: yes
    name: "{{ littlesis_app_packages }}"
  tags: packages

- import_tasks: nodejs.yml
  tags: nodejs

- import_tasks: scripts.yml
  tags: scripts

- import_tasks: redis.yml
  tags: redis

- import_tasks: manticore.yml
  tags: manticore

# - import_tasks: firefox.yml
#   tags: firefox

- import_tasks: ruby.yml
  tags: ruby

# the variable littlesis_rails_version sets the git branch or commit
- import_tasks: rails.yml
  tags: deploy

- import_tasks: nginx.yml
  become: true
  tags:
    - server
    - nginx

- import_tasks: puma.yml
  become: true
  tags:
    - server
    - puma

- import_tasks: static.yml
  tags: static

- import_tasks: logs.yml
  tags: logs
