---
- name: Install nginx
  apt:
    name: nginx

- name: Create /etc/nginx/certs folder
  file:
    path: /etc/nginx/certs
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: nginx-config

- name: Copy TLS Cert
  copy:
    content: "{{ tls_certificate }}"
    dest: /etc/nginx/certs/certificate.pem
    owner: root
    group: root
    mode: 0600
  tags: nginx-config
  no_log: true

- name: Copy TLS Key
  copy:
    content: "{{ tls_key }}"
    dest: /etc/nginx/certs/key.pem
    owner: root
    group: root
    mode: 0600
  tags: nginx-config
  no_log: true

- name: Copy nginx configuration
  template:
    src: "{{ nginx_conf_template | default('nginx.conf.j2') }}"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  tags: nginx-config
  notify: reload nginx

- name: Copy realip configuration
  copy:
    src: realip.conf
    dest: /etc/nginx/conf.d/realip.conf
    owner: root
    group: root
    mode: 0644
  tags: nginx-config
  notify: reload nginx

- name: Copy nginx ssl configuration
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/ssl.conf
    owner: root
    group: root
    mode: 0644
  tags: nginx-config
  notify: reload nginx

- name: Copy littlesis.org nginx configuration
  template:
    src: littlesis.org.j2
    dest: /etc/nginx/sites-enabled/littlesis.org
    owner: root
    group: root
    mode: 0644
  tags: nginx-config
  notify: reload nginx

- name: Copy api.littlesis.org nginx configuration
  copy:
    src: api.littlesis.org
    dest: /etc/nginx/sites-enabled/api.littlesis.org
    owner: root
    group: root
    mode: 0644
  tags: nginx-config
  notify: reload nginx
  when: "not 'staging' in group_names"

- name: Copy nginx logrotate script
  become: true
  copy:
    src: logrotate/nginx
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0640
  tags: logrotate
