---
- name: Install Redis
  become: yes
  apt:
    name: redis
    state: latest
    default_release: buster-backports

- name: Copy redis config
  become: yes
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0640'
  notify: restart redis

- name: Ensure redis is running
  become: yes
  systemd:
    state: started
    name: redis
