---
- name: Install rbenv build depends
  become: yes
  apt:
    pkg:
      - autoconf
      - bison
      - build-essential
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
    state: present
    install_recommends: no

- name: Clone rbenv
  become: yes
  become_user: littlesis
  ignore_errors: yes
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/littlesis/.rbenv
    force: yes
    version: master

- name: Configure + make rbenv
  become: yes
  become_user: littlesis
  ignore_errors: yes
  command:
    cmd: src/configure && make -C src
    chdir: /home/littlesis/.rbenv

- name: Create rbenv/plugins folder
  become: yes
  file:
    path: /home/littlesis/.rbenv/plugins
    state: directory
    owner: littlesis
    group: littlesis
    recurse: yes

- name: Clone ruby-build
  become: yes
  become_user: littlesis
  ignore_errors: yes
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/littlesis/.rbenv/plugins/ruby-build
    force: yes
    version: master

- name: Check if ruby version is installed
  become: yes
  become_user: littlesis
  shell: "/home/littlesis/.rbenv/bin/rbenv versions | grep {{ ruby_version }}"
  register: check_rbenv_versions
  failed_when: check_rbenv_versions.rc > 1

- name: Install new ruby version
  become: yes
  become_user: littlesis
  shell: "/home/littlesis/.rbenv/bin/rbenv install {{ ruby_version }}"
  when: check_rbenv_versions.rc == 1

- name: Rbenv Rehash
  become: yes
  become_user: littlesis
  shell: "/home/littlesis/.rbenv/bin/rbenv rehash"

- name: Install bundler
  become: yes
  become_user: littlesis
  gem:
    executable: "/home/littlesis/.rbenv/versions/{{ ruby_version }}/bin/gem"
    name: bundler
    state: latest
    user_install: no
  tags: bundler
