---
littlesis_app_packages:
  - imagemagick
  - libmariadb-dev
  - sqlite3
  - libsqlite3-dev

geckodriver_url: "https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz"
geckodriver_checksum: "sha255:61bfc547a623d7305256611a81ecd24e6bf9dac555529ed6baeafcf8160900da"

# Manticore
manticore_url: "https://repo.manticoresearch.com/repository/manticoresearch_buster/pool/m/manticore/manticore_3.5.4-201211-13f8d08d_amd64.deb"
manticore_checksum: "sha256:cb7d8105067fa5822aa7e85d11ab4208db1f1976793c1f31b621f0b148b48ee8"
manticore_reinstall: false

scripts_directory: /home/maintainer/scripts

database_littlesis_name: littlesis
