---
- hosts: app
  become: true
  vars_files:
    - "vars.yml"
  vars:
    littlesis_app_role: app
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: app
