---
- hosts: app
  become: true
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: rclone
      tags: rclone
    - import_role:
        name: app
  tags: app
    
- hosts: database
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: database
      vars:
        database_role: main
  tags: database
  
- hosts: replicant
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: rclone
    - import_role:
        name: database
      vars:
        database_role: replicant
  tags: replicant

- hosts: wordpress
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: rclone
    - import_role:
        name: wordpress
  tags: wordpress
