---
- name: App Server
  import_playbook: app.yml

- name: Database Server
  import_playbook: database.yml

- name: Replicant Server
  import_playbook: replicant.yml

- name: Wordpress Server
  import_playbook: wordpress.yml
