---
- hosts: app
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  roles: ["common"]
    
# - hosts: littlesis:database
#   roles: ["database"]
#   handlers: include=handlers/main.yml

# - hosts: littlesis:wordpress
#   roles: ["wordpress"]
#   handlers: include=handlers/main.yml

# - hosts: littlesis:replicant
#   roles: ["replicant"]
#   handlers: include=handlers/main.yml
