# ---
# - hosts: app
#   vars_files:
#     - "vars.yml"
#   handlers:
#     - include: handlers/main.yml
#   roles:
#     - common
#   tags: app
    
- hosts: database
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  roles:
#    - common
    - database
  tags: database


# - hosts: littlesis:wordpress
#   roles: ["wordpress"]
#   handlers: include=handlers/main.yml

# - hosts: littlesis:replicant
#   roles: ["replicant"]
#   handlers: include=handlers/main.yml
