---
- hosts: app
  become: true
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: app
    - import_role:
        name: aws
  tags: app
    
- hosts: database
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  tasks:
    # - import_role:
    #     name: common
    - import_role:
        name: aws
    - import_role:
        name: database
      vars:
        database_role: main
  tags: database
  
- hosts: replicant
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: database
      vars:
        database_role: replicant
  tags: replicant

# - Hosts: littlesis:wordpress
#   roles: ["wordpress"]
#   handlers: include=handlers/main.yml

# - hosts: littlesis:replicant
#   roles: ["replicant"]
#   handlers: include=handlers/main.yml
