---
- hosts: app
  become: true
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  roles:
    - common
    - app
    - aws
  tags: app
    
- hosts: database
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  roles:
    - common
    - database
  tags: database

# - Hosts: littlesis:wordpress
#   roles: ["wordpress"]
#   handlers: include=handlers/main.yml

# - hosts: littlesis:replicant
#   roles: ["replicant"]
#   handlers: include=handlers/main.yml
