---
- hosts: replicant
  vars_files:
    - "vars.yml"
  vars:
    database_role: replicant
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: database
