---
- hosts: littlesis-dev
  remote_user: ubuntu
  become: yes

  vars:
    server_name: dev.littlesis.org
    blog_server_name: devnews.littlesis.org
    littlesis_rails_version: cmp

  pre_tasks:
    - name: load secret vars from ~/littlesis-dev.yml
      include_vars:
        file: ~/littlesis-dev.yml
      tags: always

  roles:
    - littlesis
