---
- hosts: wordpress
  vars_files:
    - "vars.yml"
  handlers:
    - include: handlers/main.yml
  tasks:
    - import_role:
        name: common
    - import_role:
        name: rclone
    - import_role:
        name: wordpress
