---
- hosts: littlesis-wordpress-dev
  remote_user: ubuntu
  become: yes

  vars:
    swapfile_size: 1G
    news_server_name: newsdev.littlesis.org
    pai_server_name:  dev.public-accountability.org

  pre_tasks:
    - name: load secret vars from ~/littlesis.yml
      include_vars:
        file: ~/littlesis.yml
      tags: always

  roles:
    - common
    - wordpress
